//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_SPARE.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JADMEntities : DbContext
    {
        public JADMEntities()
            : base("name=JADMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<T001_COLABORADOR> T001_COLABORADOR { get; set; }
        public virtual DbSet<T002_CENTROCUSTO> T002_CENTROCUSTO { get; set; }
        public virtual DbSet<T003_TIPOCOLABORADOR> T003_TIPOCOLABORADOR { get; set; }
        public virtual DbSet<T004_CARGO> T004_CARGO { get; set; }
        public virtual DbSet<T005_SETOR> T005_SETOR { get; set; }
        public virtual DbSet<T006_TURNO> T006_TURNO { get; set; }
        public virtual DbSet<T007_SISTEMA> T007_SISTEMA { get; set; }
        public virtual DbSet<T008_MENU> T008_MENU { get; set; }
        public virtual DbSet<T009_PERFIL> T009_PERFIL { get; set; }
        public virtual DbSet<T011_GRUPO> T011_GRUPO { get; set; }
        public virtual DbSet<T012_GRUPO_EMAIL> T012_GRUPO_EMAIL { get; set; }
        public virtual DbSet<T014_PERFIL_COLABORADOR> T014_PERFIL_COLABORADOR { get; set; }
        public virtual DbSet<T015_CLIENTE> T015_CLIENTE { get; set; }
        public virtual DbSet<T016_GRUPO_CLIENTE> T016_GRUPO_CLIENTE { get; set; }
        public virtual DbSet<T017_EMPRESA> T017_EMPRESA { get; set; }
        public virtual DbSet<T018_FUNCAO> T018_FUNCAO { get; set; }
        public virtual DbSet<T020_CENTRO_CUSTO_APROVADOR> T020_CENTRO_CUSTO_APROVADOR { get; set; }
        public virtual DbSet<T022_AREA> T022_AREA { get; set; }
        public virtual DbSet<T023_AREA_COLABORADOR> T023_AREA_COLABORADOR { get; set; }
        public virtual DbSet<T025_PROFITCENTER> T025_PROFITCENTER { get; set; }
        public virtual DbSet<T026_CLASSIFICACAO> T026_CLASSIFICACAO { get; set; }
        public virtual DbSet<T027_ADM_JADM> T027_ADM_JADM { get; set; }
        public virtual DbSet<T029_PERFIL_SISTEMA> T029_PERFIL_SISTEMA { get; set; }
        public virtual DbSet<T024_ADCOLABORADOR> T024_ADCOLABORADOR { get; set; }
    }
}
