//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_SPARE.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class T001_COLABORADOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T001_COLABORADOR()
        {
            this.T014_PERFIL_COLABORADOR = new HashSet<T014_PERFIL_COLABORADOR>();
            this.T020_CENTRO_CUSTO_APROVADOR = new HashSet<T020_CENTRO_CUSTO_APROVADOR>();
            this.T023_AREA_COLABORADOR = new HashSet<T023_AREA_COLABORADOR>();
            this.T011_GRUPO = new HashSet<T011_GRUPO>();
            this.T002_CENTROCUSTO1 = new HashSet<T002_CENTROCUSTO>();
            this.T005_SETOR = new HashSet<T005_SETOR>();
        }
    
        public long T001_IDCOLABORADOR { get; set; }
        public long T001_CONTROLE { get; set; }
        public string T001_CRACHA { get; set; }
        public string T001_LOGIN { get; set; }
        public string T001_NOME { get; set; }
        public string T001_EMAIL { get; set; }
        public string T001_TELEFONE { get; set; }
        public string T001_CELULAR { get; set; }
        public Nullable<int> T002_IDCENTROCUSTO { get; set; }
        public Nullable<int> T003_IDTIPOCOLABORADOR { get; set; }
        public Nullable<int> T004_IDCARGO { get; set; }
        public Nullable<int> T006_IDTURNO { get; set; }
        public Nullable<System.DateTime> T001_DTCADASTRO { get; set; }
        public string T001_FGATIVO { get; set; }
        public string T001_FGFERIAS { get; set; }
        public string T001_TPCOLABORADOR { get; set; }
        public Nullable<int> T005_IDSETOR { get; set; }
        public Nullable<long> T001_GESTORFUNC { get; set; }
        public string T001_CPF { get; set; }
    
        public virtual T002_CENTROCUSTO T002_CENTROCUSTO { get; set; }
        public virtual T003_TIPOCOLABORADOR T003_TIPOCOLABORADOR { get; set; }
        public virtual T004_CARGO T004_CARGO { get; set; }
        public virtual T006_TURNO T006_TURNO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T014_PERFIL_COLABORADOR> T014_PERFIL_COLABORADOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T020_CENTRO_CUSTO_APROVADOR> T020_CENTRO_CUSTO_APROVADOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T023_AREA_COLABORADOR> T023_AREA_COLABORADOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T011_GRUPO> T011_GRUPO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T002_CENTROCUSTO> T002_CENTROCUSTO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T005_SETOR> T005_SETOR { get; set; }
    }
}
