//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_SPARE.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class T002_CENTROCUSTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T002_CENTROCUSTO()
        {
            this.T001_COLABORADOR = new HashSet<T001_COLABORADOR>();
            this.T020_CENTRO_CUSTO_APROVADOR = new HashSet<T020_CENTRO_CUSTO_APROVADOR>();
            this.T001_COLABORADOR1 = new HashSet<T001_COLABORADOR>();
        }
    
        public int T002_IDCENTROCUSTO { get; set; }
        public string T002_CODIGO { get; set; }
        public string T002_DESCRICAO { get; set; }
        public string T002_ATIVO { get; set; }
        public Nullable<int> T017_IDEMPRESA { get; set; }
        public Nullable<int> T025_IDPROFITCENTER { get; set; }
        public Nullable<int> T026_IDCLASSIFICACAO { get; set; }
        public Nullable<int> T005_IDSETOR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T001_COLABORADOR> T001_COLABORADOR { get; set; }
        public virtual T005_SETOR T005_SETOR { get; set; }
        public virtual T017_EMPRESA T017_EMPRESA { get; set; }
        public virtual T025_PROFITCENTER T025_PROFITCENTER { get; set; }
        public virtual T026_CLASSIFICACAO T026_CLASSIFICACAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T020_CENTRO_CUSTO_APROVADOR> T020_CENTRO_CUSTO_APROVADOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T001_COLABORADOR> T001_COLABORADOR1 { get; set; }
    }
}
