//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_SPARE.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class T005_SETOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T005_SETOR()
        {
            this.T002_CENTROCUSTO = new HashSet<T002_CENTROCUSTO>();
            this.T001_COLABORADOR = new HashSet<T001_COLABORADOR>();
        }
    
        public int T005_IDSETOR { get; set; }
        public string T005_DESCRICAO { get; set; }
        public Nullable<long> T005_GESTORWC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T002_CENTROCUSTO> T002_CENTROCUSTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T001_COLABORADOR> T001_COLABORADOR { get; set; }
    }
}
