//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_SPARE.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class T007_SISTEMA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T007_SISTEMA()
        {
            this.T008_MENU = new HashSet<T008_MENU>();
            this.T014_PERFIL_COLABORADOR = new HashSet<T014_PERFIL_COLABORADOR>();
            this.T016_GRUPO_CLIENTE = new HashSet<T016_GRUPO_CLIENTE>();
            this.T020_CENTRO_CUSTO_APROVADOR = new HashSet<T020_CENTRO_CUSTO_APROVADOR>();
            this.T023_AREA_COLABORADOR = new HashSet<T023_AREA_COLABORADOR>();
        }
    
        public string T007_IDSISTEMA { get; set; }
        public string T007_DESCRICAO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T008_MENU> T008_MENU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T014_PERFIL_COLABORADOR> T014_PERFIL_COLABORADOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T016_GRUPO_CLIENTE> T016_GRUPO_CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T020_CENTRO_CUSTO_APROVADOR> T020_CENTRO_CUSTO_APROVADOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T023_AREA_COLABORADOR> T023_AREA_COLABORADOR { get; set; }
    }
}
