//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_SPARE.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class T011_GRUPO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T011_GRUPO()
        {
            this.T012_GRUPO_EMAIL = new HashSet<T012_GRUPO_EMAIL>();
            this.T016_GRUPO_CLIENTE = new HashSet<T016_GRUPO_CLIENTE>();
            this.T001_COLABORADOR = new HashSet<T001_COLABORADOR>();
        }
    
        public int T011_IDGRUPO { get; set; }
        public string T011_NOME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T012_GRUPO_EMAIL> T012_GRUPO_EMAIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T016_GRUPO_CLIENTE> T016_GRUPO_CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T001_COLABORADOR> T001_COLABORADOR { get; set; }
    }
}
