//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_SPARE.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class T016_GRUPO_CLIENTE
    {
        public int T015_IDCLIENTE { get; set; }
        public int T011_IDGRUPO { get; set; }
        public string T007_IDSISTEMA { get; set; }
    
        public virtual T007_SISTEMA T007_SISTEMA { get; set; }
        public virtual T011_GRUPO T011_GRUPO { get; set; }
        public virtual T015_CLIENTE T015_CLIENTE { get; set; }
    }
}
