//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_SPARE.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class T017_EMPRESA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T017_EMPRESA()
        {
            this.T002_CENTROCUSTO = new HashSet<T002_CENTROCUSTO>();
        }
    
        public int T017_IDEMPRESA { get; set; }
        public string T017_CNPJ_EMPRESA { get; set; }
        public string T017_RAZAO_SOCIAL { get; set; }
        public string T017_NOME_FANTASIA { get; set; }
        public string T017_CODIGO_SAP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T002_CENTROCUSTO> T002_CENTROCUSTO { get; set; }
    }
}
