//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_SPARE.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class T023_AREA_COLABORADOR
    {
        public long T001_IDCOLABORADOR { get; set; }
        public int T022_IDAREA { get; set; }
        public string T007_IDSISTEMA { get; set; }
    
        public virtual T001_COLABORADOR T001_COLABORADOR { get; set; }
        public virtual T007_SISTEMA T007_SISTEMA { get; set; }
        public virtual T022_AREA T022_AREA { get; set; }
    }
}
