//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_SPARE.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class T029_PERFIL_SISTEMA
    {
        public long T029_ID { get; set; }
        public int T007_IDSISTEMA { get; set; }
        public int T009_IDPERFIL { get; set; }
    }
}
